### ISSUE TITLE
Is b/g/n/ac standard available?

### ISSUE THREAD

**Issue by xdevelnet** [s3erios/urtwm#1]
Hi s3erios!

I am appreciate that someone is working on freebsd wireless drivers for modern wifi adapters. Thank you so much!

Would you kindly tell me, is a**c** available? Or you have any plans to implement it?

I'd like to achieve >500 Mbps via Netis WF2190 under FreeBSD :)

Best wishes, Xdevelnet.

**Comment by s3erios** [comment]
Hi!

ac support is not available currently in net80211 nor here;  due to that:
1) Drivers for devices with 11ac support will be merged into the tree 'as is':
 * ath10k: https://github.com/erikarn/athp
 * this driver (as a part of urtwn(4)): https://github.com/s3erios/rtwn
2) then, 11ac will be implemented in net80211(4) / merged drivers.

**Comment by xdevelnet** [comment]
Thank you for quick reply!

Well... seems like I can only wait.

Unfortunately, my kernel developing skills aren't high (actually, I almost never touched kernels), so, if I'll try to merge something - that will be complete disaster. :laughing: 

Best wishes, Xdevelnet.
